version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        NEXT_PUBLIC_YANDEX_API_KEY: ${NEXT_PUBLIC_YANDEX_API_KEY}
        AUTH_SECRET: ${AUTH_SECRET}
        AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
      NEXT_PUBLIC_YANDEX_API_KEY: ${NEXT_PUBLIC_YANDEX_API_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
      AUTH_TRUST_HOST: ${AUTH_TRUST_HOST}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}