version: '3.9'

services:
  frontend:
    image: shmatozz/rankingapp-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
